# ALTO to TEI Transformation Rules Configuration
# Version: 2.0-simple
# Description: Defines how ALTO XML elements are converted to TEI format (Simple Format)

metadata:
  version: "2.0-simple"
  description: "ALTO to TEI transformation rules using simple format"
  author: "Enhanced with simple configuration format"
  format: "simple"

# How to handle different ALTO block types
block_types:     
  GraphicZone:
    description: "Graphic/decorative elements"
    process_lines: false
    skip_content: true

  MainZone:
    description: "Main text content blocks"
    process_lines: true
    skip_content: false
    
  "MarginTextZone:note":
    description: "Footnote blocks"
    process_lines: false
    skip_content: true
    extract_footnote: true

  "MarginTextZone:outer":
    description: "Margin text content blocks"
    process_lines: true
    skip_content: false

  NumberingZone:
    description: "Page number blocks"
    process_lines: false
    skip_content: true
    extract_page_number: true
    # Special rule: if this block contains signature lines, process them as content
    process_special_lines:
      - "CustomLine:signature"
      - "CustomLine:catchword"    
  
  RunningTitleZone:
    description: "Running title blocks - preserved as form work"
    process_lines: true
    skip_content: false
    tei_element: "fw"
    attributes:
      type: "running-title"
      place: "top"

  QuireMarksZone:
    description: "QuireMarksZone"
    process_lines: true
    skip_content: false

# How to handle different ALTO line types within processed blocks
line_types:
  HeadingLine:
    description: "Header lines"
    tei_element: "head"
    attributes:
      rend: "header"
    closes:
      - "paragraph"
      - "poetry"
    standalone: true
    
  "CustomLine:paragraph_start":
    description: "Beginning of paragraph - starts a new paragraph group"
    tei_element: "p"
    action: "start_paragraph"
    closes:
      - "poetry"

    
  "CustomLine:verse":
    description: "Poetry lines"
    tei_element: "l"
    container: "lg"
    container_attributes:
      type: "verse"
    closes:
      - "paragraph"

  "CustomLine:speaker":
    description: "Speaker identification"
    tei_element: "speaker"
    attributes:
      rend: "speaker"
    closes:
      - "paragraph"
      - "poetry"

  "CustomLine:onstage":
    description: "Stage directions or onstage text"
    tei_element: "stage"
    attributes:
      type: "onstage"
    closes:
      - "paragraph"
      - "poetry"
    standalone: true

  "CustomLine:divider":
    description: "Divider or separator lines"
    tei_element: "milestone"
    attributes:
      type: "divider"
      unit: "section"
    closes:
      - "paragraph"
      - "poetry"
    standalone: true
    
  "CustomLine:catchword":
    description: "Catchwords"
    tei_element: "fw"
    attributes:
      type: "catchword"
    closes:
      - "paragraph"
      - "poetry"
    standalone: true

  "CustomLine:signature":
    description: "Signatures"
    tei_element: "fw"
    attributes:
      type: "signature"
    closes:
      - "paragraph"
      - "poetry"
    standalone: true
    
  DefaultLine:
    description: "Default line type"
    tei_element: "p"
    action: "add_to_paragraph"
  

# Patterns for recognizing footnote symbols
footnote_patterns:
  - pattern: '^\(\*+\)\s*'
    type: "asterisk"
    description: "Parenthesized asterisks: (*), (**), etc."
    
  - pattern: '^\([0-9]+\)\s*'
    type: "numeric"
    description: "Parenthesized numbers: (1), (2), etc."
    
  - pattern: '^\([a-z]+\)\s*'
    type: "alphabetic_lower"
    description: "Parenthesized lowercase letters: (a), (b), etc."
    
  - pattern: '^\([A-Z]+\)\s*'
    type: "alphabetic_upper"
    description: "Parenthesized uppercase letters: (A), (B), etc."
    
  - pattern: '^\*+\s*'
    type: "asterisk_plain"
    description: "Plain asterisks: *, **, etc."
    
  - pattern: '^[0-9]+\)\s*'
    type: "numeric_paren"
    description: "Numbers with closing paren: 1), 2), etc."
    
  - pattern: '^[a-z]+\)\s*'
    type: "alphabetic_paren"
    description: "Letters with closing paren: a), b), etc."
    
  - pattern: '^[†‡§¶#]+\s*'
    type: "special_symbols"
    description: "Special symbols: †, ‡, §, ¶, #"
    
  - pattern: '^\[[0-9]+\]\s*'
    type: "bracketed_numeric"
    description: "Bracketed numbers: [1], [2], etc."
    
  - pattern: '^\[[a-z]+\]\s*'
    type: "bracketed_alphabetic"
    description: "Bracketed letters: [a], [b], etc."

# Processing rules for specific conditions
processing_rules:
  - name: "default_paragraph_content"
    conditions:
      block_type: "Main"
      line_type: "default"
    actions:
      - action: "add_to_paragraph"
        
  - name: "poetry_grouping"
    conditions:
      block_type: "Main"
      line_type: "CustomLine:verse"
    actions:
      - action: "close_paragraph"
      - action: "ensure_container"
        element: "lg"
        attributes:
          type: "verse"
      - action: "create_line"
        element: "l"
        
  - name: "header_handling"
    conditions:
      line_type: "Header"
    actions:
      - action: "close_paragraph"
      - action: "close_poetry"
      - action: "create_standalone"
        element: "head"

# TEI element creation rules
element_creation:
  # Page break elements
  page_number:
    element: "pb"
    attributes:
      n: "page_number"  # Will be replaced with actual page number
      facs: "source_image"  # Will be replaced with image filename
  
  # Footnote elements  
  footnote:
    element: "note"
    attributes:
      type: "footnote"
      n: "symbol"  # Will be replaced with footnote symbol
    container: "div"
    container_attributes:
      type: "notes"
  
  # Poetry container
  poetry_container:
    element: "lg"
    attributes:
      type: "verse"
  
  # Poetry line
  poetry_line:
    element: "l"
  
  # Form work elements (catchwords, signatures, etc.)
  form_work:
    element: "fw"
    attributes:
      type: "placeholder"  # Will be replaced by line_type mapping
    type_mappings:
      "CustomLine:catchword": "catchword"
      "CustomLine:signature": "signature"
      "default": "other"
  
  # Header elements
  header:
    element: "head"
    default_attributes:
      rend: "header"
  
  # Line break elements
  line_break:
    element: "lb"
    self_closing: true
  
  # Book-specific element creation rules
  book_page_break:
    element: "pb"
    attributes:
      n: "page_number"
      facs: "facs_reference"  # Can be surface ID or image filename
    supports_templates: true
    
  book_facsimile_surface:
    element: "surface"
    attributes:
      xml:id: "surface_id"
      lrx: "width"
      lry: "height"
    children:
      - element: "graphic"
        attributes:
          url: "image_file"
          
  book_facsimile_zone:
    element: "zone"
    attributes:
      xml:id: "zone_id"
      ulx: "ulx"
      uly: "uly"
      lrx: "lrx"
      lry: "lry"
    optional_attributes:
      baseline: "baseline"
      points: "polygon"

# TEI document structure settings
tei_structure:
  root_element: "TEI"
  namespace: "http://www.tei-c.org/ns/1.0"
  include_facsimile: true
  
  header:
    required: true
    title_source: "sourceImageInformation/fileName"
    title_prefix: "Digital text from "
    title_fallback: "Digital text from eScriptorium"
    publisher: "eScriptorium"
    source_description: "Transcribed from digital image using eScriptorium"
    
  body:
    auto_paragraph: true
    preserve_whitespace: false
    preserve_line_breaks: true  # Add <lb/> elements to preserve original line structure
    line_break_element: "lb"
    
# Book-specific processing configuration
book_processing:
  # Facsimile generation patterns
  facsimile_patterns:
    block_id: "facs_block_{page_number}_{block_index}"
    line_id: "facs_line_{page_number}_{block_index}_{line_index}"
    surface_id: "surface_{page_number}"
    zone_reference: "#{zone_id}"
    
  # Page break configuration  
  page_breaks:
    element: "pb"
    templates:
      n_template: "{page_number}"
      facs_template: "#{surface_id}"
      facs_fallback: "{filename}.jpeg"
      
  # Cross-page content handling
  cross_page_merging:
    enabled: true
    merge_paragraphs: true
    preserve_line_structure: true
    
  # Book structure
  structure:
    create_book_div: true
    div_type: "book"
    header_title_template: "Book converted from ALTO (pages {first_page}-{last_page})"
    
  # Special processing rules for specific line types
  special_line_detection:
    signature_line_label: "CustomLine:signature"  # Look for this label in ALTO tags
    catchword_line_label: "CustomLine:catchword"  # Could be used for catchwords too
    
  # Elements that should receive facsimile references
  facsimile_eligible_elements:
    - "p"
    - "lg"
    - "head"
    - "fw"
    - "div"
    - "note"
    
  # Elements to skip during content processing
  skip_elements:
    - "pb"
    - "{namespace}pb"
    
  # File format configuration
  file_formats:
    default_image_extension: ".jpeg"
    alto_extension: ".xml"
